### PR TITLE
% Inverted the "on" and "off" behaviour, using the grey color to indi…

### PR DESCRIPTION
**Pull request by JeffSkyrunner**
…cate the card deactivation

+ Updated the Unity version

### CODE REVIEW

**Comment by JeffSkyrunner** [comment]
This is linked to [this issue](https://github.com/dagguh/data-hunt/issues/25)

**Comment by dagguh** [comment]
image
Hmm, it leads to an interesting effect. Only the Sure Gamble is dimmed (slightly). So as a newcomer to the UI, I see the stolen agenda, the installed Mongoose, my id, enemy cards and enemy credits or my clicks. And I don't know that I can use some of them and some are not meant to be interactive. Dimming inactive elements would mean dimming almost all of them, most of the screen.
The initial idea behind #25 was to make the highlights stand out more. Perhaps some particle effects, glow, subtle animation (micro-shaking?). Make it feel more alive and vibrant.
What do you think?

**Comment by JeffSkyrunner** [comment]
Uhm... I see your point and definitely agree that would be better from newcomers' point of view.

In my opinion we have two way to approach this:

1. Accept this merge from an "agile" point of view: we can consider this as an improvement of the actual UI and ship this while adding a new issue to improve the behavior as you correctly suggested;
2. Reject this and wait for the proper improvement you suggested

**Comment by dagguh** [comment]
I'm in favor of merging even slight improvements, but I'm afraid that this one is a small regression. Beforehand, _all_ playable elements were consistently highlighted. Now, _some_ of playable elements are not dimmed. Would you agree to revisit this with a different approach later on?

**Comment by JeffSkyrunner** [comment]
I would, but I don't know when I would be able to do so, since my current
hardware situation :)

So I would suggest to reject the pull request and unassign the issue, in
case someone would be able to pick this up.

**Pull request closed without merging**
